### ISSUE TITLE
Releasing brim on pypi

### ISSUE THREAD

**Issue by tjstienstra** [mechmotum/symbrim#37]
When trying to publish brim on pypi I ran into the following issue:
```
HTTP Error 400: Invalid value for requires_dist. Error: Can't have direct dependency: 'sympy @ git+https://github.com/sympy/sympy.git' | b"<html>\n <head>\n  <title>400 Invalid value for requires_dist. Error: Can't have direct depen
dency: 'sympy @ git+https://github.com/sympy/sympy.git'\n \n <body>\n  <h1>400 Invalid value for requires_dist. Error: Can't have direct dependency: 'sympy @ git+https://github.com/sympy/sympy.git'\n  The server could not comply wit
h the request since it is either malformed or otherwise incorrect.<br/><br/>\nInvalid value for requires_dist. Error: Can&#x27;t have direct dependency: &#x27;sympy @ git+https://github.com/sympy/sympy.git&#x27;\n\n\n \n"
```

**Comment by TJStienstra** [comment]
The above issue has been solved by giving installation instructions in the README and temporary removing those from the `pyproject.toml` file. I've succeeded to publish `brim` on [PyPi testing](https://test.pypi.org/project/brim/). The problem that however remains is that it PyPi says that the name is not allowed:
```
$ poetry publish

Publishing brim (0.0.1) to PyPI
 - Uploading brim-0.0.1-py3-none-any.whl FAILED

HTTP Error 400: The name 'brim' isn't allowed. See https://pypi.org/help/#project-name for more information. | b"<html>\n <head>\n  <title>400 The name 'brim' isn't allowed. See https://pypi.org/help/#project-name for more information.\n \n <body>\
n  <h1>400 The name 'brim' isn't allowed. See https://pypi.org/help/#project-name for more information.\n  The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>\nThe name &#x27;brim&#x27; isn&#x
27;t allowed. See https://pypi.org/help/#project-name for more information.\n\n\n \n"
```

**Comment by moorepants** [comment]
Some names are taken on pypi but that isn't apparent from a search. For example, cyipopt was taken but didn't show up in a search. I then had to put in a request for the name and they eventually gave it to me because it was found it was never used and someone was just parking on it.

**Comment by moorepants** [comment]
It seems you are depending on dev versions of software. For pip installs to work I think you really need to depend on released versions of dependencies. If we need to make a BicycleParameters release, etc. then I can help with that. The whole pypi and conda systems rely on released versions with specific version numbers, otherwise things can be resolved with dependency resolvers in the installation tools.

**Comment by TJStienstra** [comment]
the problem is that it is depedent on `System` from sympy

**Comment by TJStienstra** [comment]
I've opened [a request](https://github.com/pypi/support/issues/2843)

**Comment by moorepants** [comment]
> I've opened https://github.com/pypi/support/issues/2843

I think it took quite some months when I made the cyipopt request, fyi.

**Comment by moorepants** [comment]
> the problem is that it is depedent on System from sympy

Quite annoying that these things didn't get into 1.12. We should have tagged these prs as needing to go into 1.12.

Maybe we should try to do a new release for sympy soon.

**Comment by TJStienstra** [comment]
they are experimental and so is `brim`, so I do agree with them not being in 1.12

**Comment by moorepants** [comment]
Then it's probably best not to release to pypi yet.
